---
- name: Clone inescoin-blockchain.git
  git:
    repo: git@github.com:inescoin/inescoin-blockchain.git
    dest: /opt/
    force: true
    accept_hostkey: true

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Composer install project
  composer: command=install working_dir=/opt/ optimize_autoloader=no

- name: Set date.timezone for CLI
  become: true
  lineinfile:
    dest: /etc/php/7.3/cli/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = UTC"

- name: Update PHP.ini include_path directories
  become: true
  lineinfile:
    dest: /etc/php/7.3/cli/php.ini
    regexp: ';include_path = ".:/php/includes"'
    line: 'include_path = ".:/php/includes:/opt/src:/opt/vendor"'

- name: Update Elasticsearch App host
  become: true
  lineinfile:
    dest: /opt/src/core/ES/ESService.php
    regexp: "elasticsearch:9200"
    line: "->setHosts(['localhost:9200'])"


